In [1]:
import pandas as pd
import numpy as np

In [2]:
import pandas as pd
import numpy as np
xl = pd.ExcelFile('Employee-wo-protected.xlsx')
df = pd.read_excel(xl, 'X', header=0)
df.head()

Education  JoiningYear  City  PaymentTier  EverBenched  \
0          0         2017     0            3            0   
1          0         2013     2            1            0   
2          0         2014     1            3            0   
3          1         2016     0            3            0   
4          1         2017     2            3            0   

   ExperienceInCurrentDomain  
0                          0  
1                          3  
2                          2  
3                          5  
4                          2

In [3]:
y = pd.read_excel(xl, 'Y', header = 0)
y.head(5)

LeaveOrNot
0           0
1           1
2           0
3           1
4           1

In [4]:
df = df.iloc[1:]

In [5]:
y = y.iloc[:, 0]

In [6]:
y[:5]

0    0
1    1
2    0
3    1
4    1
Name: LeaveOrNot, dtype: int64

In [7]:
y.unique()

array([0, 1], dtype=int64)

In [8]:
y1 = np.zeros([df.shape[0], len(y.unique())])
y1 = pd.DataFrame(y1)

In [9]:
len(df)

4652

In [10]:
len(y)

4653

In [11]:
y.unique()

array([0, 1], dtype=int64)

In [12]:
for i in range(0, len(y.unique())):
    for j in range(0, len(y1)):
        if y[j] == y.unique()[i]:
            y1.iloc[j, i] = 1
        else: 
            y1.iloc[j, i] = 0
y1.head()       

0    1
0  1.0  0.0
1  0.0  1.0
2  1.0  0.0
3  0.0  1.0
4  0.0  1.0

In [13]:
y1.tail()

0    1
4647  1.0  0.0
4648  1.0  0.0
4649  0.0  1.0
4650  0.0  1.0
4651  1.0  0.0

In [14]:
y1.shape

(4652, 2)

In [15]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])

In [16]:
theta.shape

(7, 2)

In [17]:
X = pd.concat([pd.Series(1, index=df.index, name='00'), df], axis=1)

In [18]:
X.shape

(4652, 7)

In [19]:
theta = np.ones(df.shape[1]+1)
def hypothesis(theta, X):
    return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001

In [20]:
theta.shape

(7,)

In [21]:
h = hypothesis(theta, X)

In [22]:
def cost(X, y, theta):
    y1 = hypothesis(X, theta)
    return -(1/len(X)) * np.sum(y*np.log(y1) + (1-y)*np.log(1-y1))    

In [23]:
theta = pd.DataFrame(theta)

In [24]:
type(theta.iloc[:,0])

pandas.core.series.Series

In [25]:
def gradient_descent(X, y, theta, alpha, epochs):
    m = len(X)
    #cost = [[] for i in range(10)]
    for i in range(0, epochs):
        for j in range(0, 2):
            theta = pd.DataFrame(theta)
            h = hypothesis(theta.iloc[:,j], X)
            for k in range(0, theta.shape[0]):
                theta.iloc[k, j] -= (alpha/m) * np.sum((h-y.iloc[:, j])*X.iloc[:, k])
            theta = pd.DataFrame(theta)
            #c =cost(X, y.iloc[:, j], theta.iloc[:,j])
            #cost[j].append(c)
    return theta      

In [26]:
theta = np.zeros([df.shape[1]+1, y1.shape[1]])
theta = gradient_descent(X, y1, theta, 0.02, 2000)

<ipython-input-19-7dcfc0aefaf9>:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001


In [27]:
theta

0          1
0   0.009611  -0.009495
1  -0.792998   0.793026
2  12.926946 -12.693957
3  -3.204438   3.204528
4   2.132612  -2.132301
5   0.000000   0.000000
6   0.936491  -0.936162

In [28]:
def predict(X, y):
    #theta1 = gradient_descent(X, y, theta, alpha, epochs)
    accuracy = 0
    for i in range(2):
        h = hypothesis(theta1.iloc[:,j], X)
        for n in range(0, len(h)):
            if h[n] >= 0.5 and y1.iloc[n, i] == 1:
                accuracy += 1
            elif h[n] < 0.5 and y1.iloc[n, i] == 0:
                accuracy += 1
    return accuracy       

In [29]:
theta = pd.DataFrame(theta)
hypothesis(theta.iloc[:,1], X)

<ipython-input-19-7dcfc0aefaf9>:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001


array([-1.e-07, -1.e-07, -1.e-07, ..., -1.e-07, -1.e-07, -1.e-07])

In [30]:
output = []
for i in range(0, 2):
    theta1 = pd.DataFrame(theta)
    h = hypothesis(theta1.iloc[:,i], X)
    output.append(h)
output=pd.DataFrame(output)

<ipython-input-19-7dcfc0aefaf9>:3: RuntimeWarning: overflow encountered in exp
  return 1 / (1 + np.exp(-(np.dot(theta, X.T)))) - 0.0000001


In [31]:
output

0             1             2             3             4     \
0  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01   
1 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07   

           5             6             7             8             9     ...  \
0  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  ...   
1 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07  ...   

           4642          4643          4644          4645          4646  \
0  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01   
1 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07   

           4647          4648          4649          4650          4651  
0  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  9.999999e-01  
1 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07 -1.000000e-07  

[2 rows x 4652 columns]

In [32]:
accuracy = 0
for col in range(0, 2):
    for row in range(len(y1)):
        if y1.iloc[row, col] == 1 and output.iloc[col, row] >= 0.5:
            accuracy += 1
accuracy

3052

In [33]:
accuracy= accuracy/len(X)

In [34]:
accuracy

0.6560619088564058